import { beforeEach, describe, expect, it, vi } from "vitest";
vi.mock("@/lib/firebase/admin", async () => { const fake = await import("@/lib/__testing__/firestoreFake"); return { db: fake.fakeDb, sub: fake.sub }; });
import { fakeDb } from "@/lib/__testing__/firestoreFake";
import { createPaymentForOrder, createPaymentAttempt, recordManualPayment, cancelPayment, getPaymentForOrder, PaymentDomainError } from "@/lib/payments";

const EST = "est-a"; const OTHER = "est-b"; const ORDER = "order-1";
function confirmed(establishmentId = EST, status = "confirmed") { return { id: ORDER, establishmentId, status, version: 7, snapshot: { totalCents: 2590, payment: { method: "pix" } } }; }
beforeEach(async () => { fakeDb.reset(); });
async function seed(order = confirmed()) { await fakeDb.collection(`establishments/${order.establishmentId}/orders`).doc(ORDER).set(order); }

describe("Payments Core", () => {
  it("só nasce de snapshot confirmado, em BRL e com o total congelado", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); expect(payment).toMatchObject({ amountCents: 2590, currency: "BRL", orderVersion: 7, method: "manual_pix", status: "awaiting_customer" }); });
  it("rejeita draft, tenant divergente e criação sem pedido", async () => { await seed(confirmed(EST, "draft")); await expect(createPaymentForOrder(EST, ORDER)).rejects.toMatchObject({ code: "order_not_confirmed" }); fakeDb.reset(); await seed(confirmed(OTHER)); await expect(createPaymentForOrder(EST, ORDER)).rejects.toMatchObject({ code: "not_found" }); });
  it("criação idempotente e concorrente converge para um Payment", async () => { await seed(); const results = await Promise.all([createPaymentForOrder(EST, ORDER), createPaymentForOrder(EST, ORDER)]); expect(results[0]?.id).toBe(results[1]?.id); });
  it("attempts são idempotentes e múltiplas tentativas têm ordinais", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); const [a, same] = await Promise.all([createPaymentAttempt(EST, payment.id, "intent-1"), createPaymentAttempt(EST, payment.id, "intent-1")]); const b = await createPaymentAttempt(EST, payment.id, "intent-2"); expect(a.id).toBe(same.id); expect([a.ordinal, b.ordinal]).toEqual([1, 2]); });
  it("confirmação manual é auditável e duplicada com a mesma intenção é idempotente", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); const paid = await recordManualPayment(EST, payment.id, payment.version, "confirm-1", "owner-a"); const same = await recordManualPayment(EST, payment.id, payment.version, "confirm-1", "owner-a"); expect(same).toEqual(paid); expect((await getPaymentForOrder(EST, ORDER))?.status).toBe("paid"); });
  it("duas confirmações concorrentes deixam uma única mutação financeira", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); const results = await Promise.allSettled([recordManualPayment(EST, payment.id, 1, "a", "owner-a"), recordManualPayment(EST, payment.id, 1, "b", "owner-b")]); expect(results.filter((r) => r.status === "fulfilled")).toHaveLength(1); });
  it("paid não volta a processing e cancelamento usa versionamento", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); const paid = await recordManualPayment(EST, payment.id, 1, "a", "owner-a"); await expect(cancelPayment(EST, paid.id, paid.version, "owner-a")).rejects.toMatchObject({ code: "invalid_transition" }); const another = await createPaymentForOrder(EST, ORDER); expect(another.status).toBe("paid"); });
  it("cancelamento pendente é idempotente e preserva isolamento de tenant", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); await expect(cancelPayment(OTHER, payment.id, payment.version, "owner-b")).rejects.toMatchObject({ code: "not_found" }); const cancelled = await cancelPayment(EST, payment.id, payment.version, "owner-a"); expect(cancelled.status).toBe("cancelled"); await expect(cancelPayment(EST, payment.id, cancelled.version, "owner-a")).resolves.toMatchObject({ status: "cancelled" }); });
  it("não introduz billing SaaS nem dados de cartão no Payment", async () => { await seed(); const payment = await createPaymentForOrder(EST, ORDER); expect(payment).not.toHaveProperty("billing"); expect(JSON.stringify(payment)).not.toMatch(/pan|cvv|token/i); });
});
