"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import type { MenuImageImport, MenuImportPreview } from "@/types";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input, Label } from "@/components/ui/Field";

const money = (value: number | null) => value === null ? "" : (value / 100).toFixed(2).replace(".", ",");
const parseMoney = (value: string) => { const parsed = Math.round(Number(value.replace(",", ".")) * 100); return Number.isInteger(parsed) && parsed >= 0 ? parsed : null; };
const label: Record<MenuImageImport["status"], string> = { processing: "Processando", ready: "Pronto para revisão", failed: "Falhou", confirmed: "Importado" };

export function MenuImageImporter({ onConfirmed }: { onConfirmed: () => void }) {
  const [items, setItems] = useState<MenuImageImport[]>([]); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  const load = useCallback(async () => { const response = await fetch("/api/menu/imports"); if (response.ok) setItems((await response.json()).imports ?? []); }, []);
  useEffect(() => { load(); }, [load]);
  const uploadOne = async (file: File) => { const body = new FormData(); body.set("file", file); const response = await fetch("/api/menu/imports", { method: "POST", body }); const json = await response.json().catch(() => ({})); if (!response.ok) return { item: { id: `local-${crypto.randomUUID()}`, establishmentId: "", hash: "", fileName: file.name, mimeType: file.type, byteSize: file.size, status: "failed" as const, attemptCount: 0, preview: null, errorCode: json.error ?? "Falha no upload", createdAt: Date.now(), updatedAt: Date.now(), confirmedAt: null } satisfies MenuImageImport }; return { item: json.item as MenuImageImport }; };
  const upload = async (files: FileList | null) => { if (!files?.length) return; setBusy(true); const list = [...files]; const results: Awaited<ReturnType<typeof uploadOne>>[] = []; for (let i = 0; i < list.length; i += 2) results.push(...await Promise.all(list.slice(i, i + 2).map(uploadOne))); setItems((old) => { const byId = new Map(old.map((item) => [item.id, item])); for (const result of results) byId.set(result.item.id, result.item); return [...byId.values()].sort((a, b) => b.updatedAt - a.updatedAt); }); setBusy(false); if (input.current) input.current.value = ""; };
  const edit = (item: MenuImageImport, preview: MenuImportPreview) => setItems((all) => all.map((current) => current.id === item.id ? { ...current, preview } : current));
  const save = async (item: MenuImageImport) => { const response = await fetch(`/api/menu/imports/${item.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ preview: item.preview }) }); if (response.ok) { const json = await response.json(); setItems((all) => all.map((x) => x.id === item.id ? json.item : x)); } };
  const confirm = async (item: MenuImageImport) => { setBusy(true); const response = await fetch(`/api/menu/imports/${item.id}/confirm`, { method: "POST" }); const json = await response.json().catch(() => ({})); if (response.ok) { setItems((all) => all.map((x) => x.id === item.id ? json.item : x)); onConfirmed(); } else alert(json.error === "preview_requires_review" ? "Corrija ou remova todos os itens marcados para revisão antes de confirmar." : "Não foi possível confirmar esta importação."); setBusy(false); };
  return <Card className="p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Importar cardápio por imagens</p><p className="mt-1 text-sm text-ink-500">Envie fotos do cardápio. Revise tudo antes de publicar: as imagens não ficam armazenadas.</p></div><Button variant="secondary" onClick={() => input.current?.click()} disabled={busy}>{busy ? "Processando…" : "Selecionar imagens"}</Button><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(event) => upload(event.target.files)} /></div>
    <div className="mt-4 space-y-3">{items.map((item) => <ImportCard key={item.id} item={item} onEdit={edit} onSave={save} onConfirm={confirm} busy={busy} />)}</div></Card>;
}
function ImportCard({ item, onEdit, onSave, onConfirm, busy }: { item: MenuImageImport; onEdit: (item: MenuImageImport, preview: MenuImportPreview) => void; onSave: (item: MenuImageImport) => void; onConfirm: (item: MenuImageImport) => void; busy: boolean }) {
  const preview = item.preview;
  return <div className="rounded-control border border-line p-3"><div className="flex items-center justify-between gap-2"><span className="truncate text-sm font-medium">{item.fileName}</span><span className="text-xs text-ink-500">{label[item.status]}</span></div>{item.status === "failed" && <p className="mt-2 text-sm text-danger-fg">{item.errorCode ?? "Falha no reconhecimento"}. Você pode enviar a imagem novamente.</p>}{preview && <div className="mt-3 space-y-3">{preview.products.map((product, index) => <div key={product.id} className="rounded-control bg-canvas-subtle p-3"><div className="flex items-center justify-between"><strong className="text-sm">Item {index + 1}</strong><Button size="sm" variant="danger" onClick={() => onEdit(item, { ...preview, products: preview.products.filter((_, i) => i !== index) })}>Excluir</Button></div><div className="mt-2 grid gap-2 sm:grid-cols-2"><div><Label>Categoria</Label><Input value={product.categoryName} onChange={(e) => onEdit(item, { ...preview, products: preview.products.map((p, i) => i === index ? { ...p, categoryName: e.target.value } : p) })} /></div><div><Label>Produto</Label><Input value={product.name} onChange={(e) => onEdit(item, { ...preview, products: preview.products.map((p, i) => i === index ? { ...p, name: e.target.value } : p) })} /></div><div><Label>Preço (R$)</Label><Input value={money(product.basePriceCents)} inputMode="decimal" onChange={(e) => onEdit(item, { ...preview, products: preview.products.map((p, i) => i === index ? { ...p, basePriceCents: parseMoney(e.target.value), reviewReasons: parseMoney(e.target.value) === null ? ["Preço ausente ou ilegível"] : p.reviewReasons.filter((reason) => reason !== "Preço ausente ou ilegível") } : p) })} /></div><div><Label hint="opcional">Descrição</Label><Input value={product.description ?? ""} onChange={(e) => onEdit(item, { ...preview, products: preview.products.map((p, i) => i === index ? { ...p, description: e.target.value || null } : p) })} /></div></div>{product.reviewReasons.length > 0 && <p className="mt-2 text-xs text-danger-fg">Revisar: {product.reviewReasons.join("; ")}</p>}{(product.variants.length > 0 || product.modifierGroups.length > 0) && <p className="mt-2 text-xs text-ink-500">Variantes/adicionais extraídos serão preservados na importação. Para ajustes detalhados, confirme e edite o produto no editor do cardápio.</p>}</div>)}{item.status === "ready" && <div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => onSave(item)}>Salvar revisão</Button><Button size="sm" disabled={busy || preview.products.length === 0} onClick={() => onConfirm(item)}>Confirmar importação</Button></div>}</div>}</div>;
}
