"use client";
import { useCallback, useEffect, useState } from "react";
import type { FoodOrder, MenuCategory, MenuProduct, OrderStatus } from "@/types";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { Input, Label, Select } from "@/components/ui/Field";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui/States";
import { PageHeader } from "@/components/ui/PageHeader";
import { StatusBadge, type StatusTone } from "@/components/ui/StatusBadge";

const money = (cents: number) => (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
const labels: Record<OrderStatus, { label: string; tone: StatusTone }> = { draft: { label: "Rascunho", tone: "neutral" }, awaiting_confirmation: { label: "Aguardando confirmação", tone: "warning" }, confirmed: { label: "Novo", tone: "warning" }, accepted: { label: "Aceito", tone: "info" }, preparing: { label: "Preparando", tone: "info" }, ready_for_pickup: { label: "Pronto para retirada", tone: "success" }, out_for_delivery: { label: "Saiu para entrega", tone: "info" }, completed: { label: "Concluído", tone: "success" }, cancelled: { label: "Cancelado", tone: "danger" }, rejected: { label: "Recusado", tone: "danger" } };
const next: Partial<Record<OrderStatus, { status: OrderStatus; label: string }[]>> = { confirmed: [{ status: "accepted", label: "Aceitar" }, { status: "rejected", label: "Recusar" }], accepted: [{ status: "preparing", label: "Preparar" }], preparing: [{ status: "ready_for_pickup", label: "Pronto para retirada" }, { status: "out_for_delivery", label: "Saiu para entrega" }], ready_for_pickup: [{ status: "completed", label: "Concluir" }], out_for_delivery: [{ status: "completed", label: "Concluir" }] };

export default function PedidosPage() {
  const [orders, setOrders] = useState<FoodOrder[]>([]); const [categories, setCategories] = useState<MenuCategory[]>([]); const [products, setProducts] = useState<MenuProduct[]>([]); const [state, setState] = useState<"loading" | "ready" | "disabled" | "error">("loading");
  const load = useCallback(async () => { setState("loading"); const [o, c, p] = await Promise.all([fetch("/api/orders"), fetch("/api/menu/categories"), fetch("/api/menu/products")]); if (o.status === 404) { setState("disabled"); return; } if (!o.ok || !c.ok || !p.ok) { setState("error"); return; } const [oj, cj, pj] = await Promise.all([o.json(), c.json(), p.json()]); setOrders(oj.orders ?? []); setCategories(cj.categories ?? []); setProducts(pj.products ?? []); setState("ready"); }, []);
  useEffect(() => { load(); }, [load]);
  const transition = async (id: string, status: OrderStatus) => { const r = await fetch(`/api/orders/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); if (r.ok) load(); };
  if (state === "loading") return <LoadingState />;
  if (state === "error") return <ErrorState onRetry={load} />;
  if (state === "disabled") return <div className="mx-auto max-w-3xl"><PageHeader title="Pedidos" /><EmptyState title="Pedidos ainda não estão habilitados" description="Ative “Permitir pedidos pela IA” em Configurações para cadastrar o cardápio e receber pedidos." /></div>;
  return <div className="mx-auto max-w-5xl"><PageHeader title="Pedidos" description="Acompanhe novos pedidos e mantenha o cliente informado pela conversa." action={<Button variant="secondary" size="sm" onClick={load}>Atualizar</Button>} />
    <section className="grid gap-4 lg:grid-cols-2"><div><h2 className="mb-3 text-lg font-bold">Fila de pedidos</h2>{orders.filter((o) => o.status !== "draft").length === 0 ? <EmptyState title="Nenhum pedido confirmado" description="Pedidos confirmados pelo WhatsApp aparecem aqui." /> : <div className="space-y-3">{orders.filter((o) => o.status !== "draft").map((o) => <Card key={o.id} className="p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{o.contactName ?? o.contactPhone}</p><p className="text-xs text-ink-500">{o.fulfillment === "delivery" ? `Entrega: ${o.deliveryAddress?.raw ?? "endereço pendente"}` : "Retirada"} · {o.payment.method ?? "pagamento pendente"}</p></div><StatusBadge tone={labels[o.status].tone}>{labels[o.status].label}</StatusBadge></div><ul className="mt-3 text-sm text-ink-700">{o.items.map((i) => <li key={i.id}>{i.quantity}× {i.productName}{i.variantName ? ` · ${i.variantName}` : ""}{i.notes ? ` (${i.notes})` : ""}</li>)}</ul><p className="mt-3 font-bold">Total: {money(o.totalCents)}</p><div className="mt-3 flex flex-wrap gap-2">{next[o.status]?.map((n) => <Button key={n.status} size="sm" onClick={() => transition(o.id, n.status)}>{n.label}</Button>)}{["confirmed", "accepted", "preparing", "ready_for_pickup", "out_for_delivery"].includes(o.status) && <Button size="sm" variant="danger" onClick={() => transition(o.id, "cancelled")}>Cancelar</Button>}</div></Card>)}</div>}</div>
    <div><h2 className="mb-3 text-lg font-bold">Cardápio</h2><MenuEditor categories={categories} products={products} onChanged={load} /></div></section></div>;
}

function MenuEditor({ categories, products, onChanged }: { categories: MenuCategory[]; products: MenuProduct[]; onChanged: () => void }) {
  const [category, setCategory] = useState(""); const [name, setName] = useState(""); const [productCategory, setProductCategory] = useState(""); const [price, setPrice] = useState(""); const [saving, setSaving] = useState(false);
  const addCategory = async () => { if (!category.trim()) return; setSaving(true); await fetch("/api/menu/categories", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: category }) }); setCategory(""); setSaving(false); onChanged(); };
  const addProduct = async () => { const cents = Math.round(Number(price.replace(",", ".")) * 100); if (!name.trim() || !productCategory || !Number.isFinite(cents) || cents < 0) return; setSaving(true); await fetch("/api/menu/products", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, categoryId: productCategory, basePriceCents: cents, active: true, variants: [], modifierGroups: [] }) }); setName(""); setPrice(""); setSaving(false); onChanged(); };
  return <div className="space-y-4"><Card className="p-4"><Label>Nova categoria</Label><div className="mt-2 flex gap-2"><Input value={category} onChange={(e) => setCategory(e.target.value)} placeholder="Ex.: Hambúrgueres" /><Button size="sm" disabled={saving} onClick={addCategory}>Adicionar</Button></div></Card><Card className="p-4"><p className="mb-3 font-semibold">Novo produto</p><div className="grid gap-3"><div><Label>Nome</Label><Input value={name} onChange={(e) => setName(e.target.value)} placeholder="X-Burguer" /></div><div><Label>Categoria</Label><Select value={productCategory} onChange={(e) => setProductCategory(e.target.value)}><option value="">Selecione</option>{categories.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</Select></div><div><Label>Preço (R$)</Label><Input value={price} onChange={(e) => setPrice(e.target.value)} inputMode="decimal" placeholder="19,90" /></div><Button disabled={saving || categories.length === 0} onClick={addProduct}>Salvar produto</Button></div></Card><Card className="p-4"><p className="mb-2 font-semibold">Produtos cadastrados</p>{products.length === 0 ? <p className="text-sm text-ink-500">Cadastre categorias e produtos. Variantes e adicionais podem ser editados pelo endpoint de produto nesta primeira versão.</p> : <ul className="space-y-2 text-sm">{products.map((p) => <li key={p.id} className="flex justify-between"><span>{p.name}{!p.active ? " · indisponível" : ""}</span><strong>{money(p.basePriceCents)}</strong></li>)}</ul>}</Card></div>;
}
